# Use of ASE

Author: [Fabien Pascale](https://www.researchgate.net/profile/Fabien_Pascale2)

ASE is a set of tools and Python modules for setting up, manipulating,
running, visualizing and analyzing atomistic simulations.
Webpage: http://wiki.fysik.dtu.dk/ase

## Creation of a specific virtual environment

```
virtualenv -p python3 venv_python3_ia
```
Loading the environment
```
source venv_python3_ia/bin/activate
```

## Installing the necessary packages with the *pip* command 

```
pip install scipy
```

## Installation

https://gitlab.com/ase/ase

- Requirements:

Python >= 3.5

NumPy >= 1.10 (base N-dimensional array package)

SciPy >= 0.17 (library for scientific computing)

- Latest Version :

Version 3.19.0

16 December 2019: 3.19.0

```
 pip install --upgrade git+https://gitlab.com/ase/ase.git@master
  
```

# Visualization of the 42-atom primitive cell

In [1]:
from ase import Atoms
from ase.io import read, write
import ase
from ase.visualize import view

atoms =ase.io.read("first_config.xyz",format="xyz")
#view(atoms, viewer='x3d')

In [2]:
view(atoms)

# Visualization of the zeolite cage by repeating the primitive mesh in the 3 directions

In [6]:
#!pip3 install nglview
from ase import Atoms
from ase.io import read, write
import ase
from ase.visualize import view

atoms =ase.io.read("first_config.xyz",format="xyz")

#view(atoms, viewer='x3d')
v=view(atoms.repeat(2), viewer='ngl')
#v.custom_colors({'Al':'purple','Si':'yellow','O':'blue','C':'grey','H':'white'})
v.view.clear_representations()
v.view.center()
v.view.background='#fff'
v.view.add_unitcell()
view.camera='orthographic'; 
v.view.add_ball_and_stick()
v.view.update_spacefill(radiusType='covalent', scale=0.20)
v.view.parameters=dict(clipDist=-100);
v

# Visualization of the trajectory of molecular dynamic

In [9]:
# Read the `MLPT.1900` file and use the MD read function. See the ASE site on visualize

# Display of the information available in the *Atoms* class (mesh parameters, atomic positions and numbers of the atoms...)

In [7]:
print("\n\ninfo\n",atoms.info)

print("\n\ncell\n",atoms.get_cell())

print("\n\nPeriodic Bounding conditions :\n",atoms.get_pbc())

print("\n\nPositions\n",atoms.get_positions())
print("\n\nSymbols\n",atoms.symbols)
print("\n\natomic numbers\n",atoms.get_atomic_numbers)

#print("\n\nall_distances\n",atoms.get_all_distances)



info
 {'energy': -311.78921226, 'stress': array([[ 0.01822526, -0.00025993,  0.00562048],
       [-0.00025993,  0.02032353, -0.00564001],
       [ 0.00562048, -0.00564001,  0.02122524]]), 'free_energy': -311.78921226}


cell
 Cell([[7.94875485, -4.997e-05, 4.90143315], [-3.97456407, 6.88389431, 4.90125479], [-3.97443877, -6.88377714, 4.90124571]])


Periodic Bounding conditions :
 [ True  True  True]


Positions
 [[ 2.06431498  0.32946941  6.6461922 ]
 [ 0.45354344 -2.90930619  4.56610161]
 [ 0.07848447 -2.05679382  5.01956828]
 [ 0.05888788 -3.80077473  5.09647066]
 [ 0.09200188 -2.92158328  3.48958824]
 [ 1.52802207 -2.91033876  4.58321789]
 [ 1.72699016 -1.20484931  4.84686198]
 [ 1.88028602 -1.16309027 12.36146257]
 [-1.03151502  5.09719259  4.83865887]
 [-4.30058622 -3.25193201  7.7401131 ]
 [-3.47592729 -0.74026586  7.74991547]
 [-2.10581263  0.33979013  9.8292381 ]
 [-1.85151994  1.49711895  2.59013662]
 [-1.73382952  1.00336303  7.25304292]
 [-0.75448625  1.90488804  4.953028

# Finding the neighbors of an atom

https://wiki.fysik.dtu.dk/asap/Neighbor%20lists

In [8]:
from ase.neighborlist import NeighborList

from ase.neighborlist import natural_cutoffs
import numpy as np
cutoffs=natural_cutoffs(atoms)
#cutoffs={(1, 6): 1.1, (1, 1): 1.0, (‘C’, ‘C’): 1.85
center=12
print(len(cutoffs))
cutoffs= [0]*42
cutoffs[center]=4.0
print(cutoffs)

nblist = NeighborList(cutoffs, self_interaction=False,bothways=True)
nblist.update(atoms)

indices, offsets = nblist.get_neighbors(center)
print("\nIndices :\n",indices)
print("\nRecherche des voisins de l'atome :\n",center," ",atoms[center].symbol,offsets,atoms.positions[center])
print("\n")
for i, offset in zip(indices, offsets):
    print(i," ",atoms[i].symbol," ",
          #atoms.get_distances(center,i),
          np.linalg.norm(atoms.positions[center] - (atoms.positions[i] + offset @ atoms.get_cell())),
          offset,atoms.positions[i] + offset @ atoms.get_cell())

#print("\n\nListe des atomes :\n")
#for i in range(0,atoms.get_number_of_atoms()):
#    print(i," ",atoms[i].symbol,atoms.positions[i])


42
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Indices :
 [27 40 19 35 14 34  0  7  8  9 23 24 29 30 31 37 39 41]

Recherche des voisins de l'atome :
 12   O [[ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [-1  0  0]
 [-1  0 -1]
 [ 0  0  0]
 [ 0  0 -1]
 [-1  0 -1]
 [-1  0 -1]
 [-1  0  0]
 [-1  0  0]
 [ 0  0 -1]
 [-1  0 -1]
 [-1  0 -1]
 [-1  0  0]] [-1.85151994  1.49711895  2.59013662]


27   O   4.486262721911126 [0 0 0] [ 1.68568664 -0.16879385  4.79001329]
40   Si   4.0450442496918 [0 0 0] [1.99283152 0.39869732 3.20398901]
19   O   2.591937810126824 [0 0 0] [0.7231232  1.34404389 2.84689008]
35   Si   1.6056079445612188 [0 0 0] [-0.59467299  2.13973532  3.35522277]
14   O   2.6368576446878613 [0 0 0] [-0.75448625  1.90488804  4.95302885]
34   Si   4.219733712618904 [0 0 0] [-0.62500295  2.00551581  6.59555062]
0   Al   4.282802254776013 [-1  0  0] [-5.88443987  0.32951938  