<a name="top"></a>
<br/>
# Machine learning thermodynamic perturbation theory (MLPT) - Distance
<br/>

**École Nationale Supérieure des Mines de Nancy**  
Project under the supervison of [Dario Rocca](http://crm2.univ-lorraine.fr/lab/fr/personnel/dario-rocca/) and [Fabien Pascale](https://www.researchgate.net/profile/Fabien_Pascale).  

Title: *High-accuracy materials modeling by machine learning quantum simulations*.  
Authors: [Lucas Lherbier](https://www.linkedin.com/in/lucas-lherbier/).

Last update: Feb 3rd, 2020.
<br/>

---
This notebook completes my project report. The Jupyter notebooks are divided in three parts : 
* the **[MLPT_position](MLPT_position.ipynb)** file: it creates the dataset whose features are the relative positions to an atom of reference.
* the **[MLPT_Distance](MLPT_Distance.ipynb)** file: it creates the dataset whose features are the distances of the neighbors from an atom of reference. For each configuration, all the atoms in the primitive cell are atoms of reference.
* the **[MLPT_Machine Learning](MLPT_MachineLearning.ipynb)** file: it applies machine learning algorithms to the datasets.

This notebook is the **MLPT_Distance** file.

---

### Imports

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

import timeit
import collections
from operator import itemgetter

import ase
from ase.io import read, write
from ase.neighborlist import NeighborList
from ase.neighborlist import natural_cutoffs

---
<a name="def"></a>

# Distance descriptors

## Files extraction

Our data deals with science materials. The data file includes one material, whose primitive cell is composed of 42 atoms. For each configuration, we get the coordinates of the atoms.
The molecule position changes with time, then the coordinates of the atoms change. 

In [2]:
atoms_2 = ase.io.read('MLPOS.19000',index=':2',format="xyz") #for test
atoms_200 = ase.io.read('MLPOS.19000',index='::95',format="xyz")
data_energy = pd.read_csv('CORRECTIONS', header = None, sep =' ', names = ['Id', 'Energy'] )  

## Neighbors

In [3]:
cutoffs = natural_cutoffs(atoms_2[1]) #Generate a radial cutoff for every atom based on covalent radii.
index = 41 #atom of reference for which we search the neighors
print('Lenght of the cutoffs:',len(cutoffs))

cutoffs= [0]*42
cutoffs[index]=4.0 #value of the radius
print('List of the cutoffs:',cutoffs)

nblist = NeighborList(cutoffs, self_interaction=False,bothways=True)
nblist.update(atoms_2[1])

indices, offsets = nblist.get_neighbors(index)
print("\nIndices: ",indices)

print("Search of the neighbors for the atom: ",index)
print("Symbol of the atom: ",atoms_2[1][index].symbol,offsets,atoms_2[1].positions[index])
print("\n")
for i, offset in zip(indices, offsets):
    print(i," ",atoms_2[1][i].symbol," ",
          atoms_2[1].get_distances(index,i),
          np.linalg.norm(atoms_2[1].positions[index] - (atoms_2[1].positions[i] + offset @ atoms_2[1].get_cell())),
          offset,atoms_2[1].positions[i] + offset @ atoms_2[1].get_cell())

Lenght of the cutoffs: 42
List of the cutoffs: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4.0]

Indices:  [19 12 14 35  0  7  9 17 18 21 22 23 24 25 26 27 29 30 31 37 38 39]
Search of the neighbors for the atom:  41
Symbol of the atom:  Si [[ 1  0  0]
 [ 1  0  0]
 [ 1  0  0]
 [ 1  0  0]
 [ 0  0  0]
 [ 0  0 -1]
 [ 1  0 -1]
 [ 0  0 -1]
 [ 0  0 -1]
 [ 0  0  0]
 [ 0  0 -1]
 [ 0  0 -1]
 [ 0  0 -1]
 [ 0  0  0]
 [ 0  0 -1]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 1  0 -1]
 [ 0  0 -1]
 [ 0  0 -1]
 [ 0  0 -1]] [4.86999972 1.95677207 6.49048597]


19   O   [5.54091632] 4.061347659519735 [1 0 0] [8.67581462 1.33608451 7.76526623]
12   O   [7.781965] 1.6398711411928233 [1 0 0] [6.10523442 1.52747042 7.47996699]
14   O   [5.85586085] 4.068104376914353 [1 0 0] [7.17147119 1.89102933 9.84434646]
35   Si   [6.30134554] 3.056229759038534 [1 0 0] [7.34620028 2.13336283 8.27312077]
0   Al   [3.22665845] 3.226658450990714 [0 0 

## Functions

We create several useful functions. In order to assess the quality of the functions, some prints are made and can be compared to the neighbors found at the [Neighbors](##Neighbors) section. The functions created are:
* `atom_get_neighbors`: return the list of the neighbors of an atom of reference, in a sphere of given radius, and for a specific configuration;  


* `nb_neighbors`: return the list of the neighbors sorted in ascending order and the number of neighbors for each type of atom; 


* `max_type_neighbors`: return the maximum numbers of the neighbors for each type of atom;


* `mol_get_neighbors`: return the list of the neighbors for all the atoms of reference for a specific configuration and also the maximums of neighbors for each atom;


* `all_config_neighbors`: return the list of the neighbors for each configuration, for all the atoms. Return also the maximum number of neighbors for each type of atom sorted alphabetically in a dictionary;


* `class_neighbors`: return the distances for each atom type in a dictionary, for a specific atom of reference;


* `get_list_distances`: return the list of the distances order by ascending for a specific atom of reference;


* `create_row`: return a row vector with all the distances for all the atoms of references for one configuration;


* `data_array`: return the final data frame;



In [4]:
def atom_get_neighbors(configuration, index, radius):
    """ Return the list of the neighbors of a specific configuration, configuration, from an atom of reference whose 
    index is index. The radius is radius, expressed in Ångström."""
    cutoffs=natural_cutoffs(configuration) #Generate a radial cutoff for every atom based on covalent radii.
    cutoffs= [0]*42
    cutoffs[index]= radius #choix du rayon

    nblist = NeighborList(cutoffs, self_interaction=False,bothways=True)
    nblist.update(configuration)
    indices, offsets = nblist.get_neighbors(index)
    
    list_neighbors = []
    for i, offset in zip(indices, offsets):
        list_neighbors.append([i,configuration[i].symbol,float(configuration.get_distances(index,i))])
    return list_neighbors
    
list_neighbors = atom_get_neighbors(atoms_2[1],41,4)
print('List of the neighbors for one spectifit atom of reference:\n', list_neighbors)

List of the neighbors for one spectifit atom of reference:
 [[19, 'O', 5.540916316997791], [12, 'O', 7.7819650009910974], [14, 'O', 5.855860846368702], [35, 'Si', 6.301345535078604], [0, 'Al', 3.226658450990714], [7, 'O', 7.2637727153269545], [9, 'O', 10.615814078724782], [17, 'O', 9.558257708994331], [18, 'O', 8.240781936512354], [21, 'O', 4.018323624679267], [22, 'O', 6.883358416437047], [23, 'O', 8.342630041336772], [24, 'O', 6.398725961359146], [25, 'O', 4.597726319507452], [26, 'O', 8.275467725041082], [27, 'O', 4.198413268295706], [29, 'O', 1.5787762843840065], [30, 'O', 1.6792019993926566], [31, 'Si', 10.370024419115662], [37, 'Si', 8.165082114215778], [38, 'Si', 6.077268148662403], [39, 'Si', 7.567778645771182]]


In [5]:
def nb_neighbors(list_neighbors):
    """ From the list of the neighbors, return the list of neighbors sorted in ascending order and the number of neighbors for each type of atom 
    in a dictionary."""
    list_neighbors = sorted(list_neighbors, key=itemgetter(2))
    list_types = []
    for i in list_neighbors : 
        list_types.append(i[1])
    list_types = dict(collections.Counter(list_types))
    return list_neighbors,list_types

list_neighbors,list_types = nb_neighbors(list_neighbors)
print('List of the neighbors sorted in ascending order:',list_neighbors)
print('Number of neighbors for each atom type:',list_types)

List of the neighbors sorted in ascending order: [[29, 'O', 1.5787762843840065], [30, 'O', 1.6792019993926566], [0, 'Al', 3.226658450990714], [21, 'O', 4.018323624679267], [27, 'O', 4.198413268295706], [25, 'O', 4.597726319507452], [19, 'O', 5.540916316997791], [14, 'O', 5.855860846368702], [38, 'Si', 6.077268148662403], [35, 'Si', 6.301345535078604], [24, 'O', 6.398725961359146], [22, 'O', 6.883358416437047], [7, 'O', 7.2637727153269545], [39, 'Si', 7.567778645771182], [12, 'O', 7.7819650009910974], [37, 'Si', 8.165082114215778], [18, 'O', 8.240781936512354], [26, 'O', 8.275467725041082], [23, 'O', 8.342630041336772], [17, 'O', 9.558257708994331], [31, 'Si', 10.370024419115662], [9, 'O', 10.615814078724782]]
Number of neighbors for each atom type: {'O': 16, 'Al': 1, 'Si': 5}


In [6]:
def max_type_neighbors(list_dic) : 
    """ From a list of a dictionary with the number of neighbors for each type of atom, return the maximums of these 
    numbers for each type of atom in a dictionary."""
    dic_neighbors_max = list_dic[0]
    for dic_neighbors_atom_i in list_dic : 
        for key, val in dic_neighbors_atom_i.items():
            if key in dic_neighbors_max : 
                if val > dic_neighbors_max[key] : 
                    dic_neighbors_max[key] = val
            else : 
                dic_neighbors_max[key] = val
    return dic_neighbors_max


def mol_get_neighbors(configuration , radius) : 
    """ From a specific configuration, configuration, return the list of the neighbors for all the atom in a sphere of
    radius radius. Return also the dictionary of the maximums of neighbors for each atom type."""
    list_all_neighbors = []
    list_all_types = []
    for center in range(42) : 
        list_neighbors = atom_get_neighbors(configuration, center, radius)
        list_neighbors,list_types = nb_neighbors(list_neighbors)
        list_all_neighbors.append(list_neighbors)
        list_all_types.append(list_types)
    list_all_types = max_type_neighbors(list_all_types)
    return list_all_neighbors,list_all_types

list_all_neighbors,list_all_types = mol_get_neighbors(atoms_2[1],4)
print('Size of list_all_neighbors = ', len(list_all_neighbors))
print('Size of the elements of list_all_neighbors = ', len(list_all_neighbors[0]))
print('List of all the neighbors type =', list_all_types ,'\n')

def all_config_neighbors(all_atom, radius):
    """ From all the atoms, return the list of the neighbors for each configuration and the maximum number of neighbors
    for each type of atom sorted alphabetically in a dictionary."""
    list_all_neighbors = []
    list_all_types = []
    for i in range(len(all_atom)) : 
        neighbors_atom_i = mol_get_neighbors(all_atom[i], radius)
        list_all_neighbors.append(neighbors_atom_i[0])
        list_all_types.append(neighbors_atom_i[1])
    list_all_types = max_type_neighbors(list_all_types)
    dic_all_types = dict()
    for key in sorted(list_all_types.items()):
        dic_all_types.update({key[0] : key[1]})
    return list_all_neighbors, dic_all_types

list_all_neighbors, dic_all_types = all_config_neighbors(atoms_2, 4)
print('Size of list_all_neighbors = ', len(list_all_neighbors))
print('Size of the elements of list_all_neighbors = ', len(list_all_neighbors[0]))
print('Size of the elements of the 1st element of list_all_neighbors = ', len(list_all_neighbors[0][0]))
print('List of all the neighbors type =', dic_all_types ,'\n')

Size of list_all_neighbors =  42
Size of the elements of list_all_neighbors =  27
List of all the neighbors type = {'O': 16, 'H': 5, 'Si': 8, 'C': 1, 'Al': 1} 

Size of list_all_neighbors =  2
Size of the elements of list_all_neighbors =  42
Size of the elements of the 1st element of list_all_neighbors =  26
List of all the neighbors type = {'Al': 1, 'C': 1, 'H': 5, 'O': 16, 'Si': 8} 



In [7]:
def class_neighbors(list_neighbors):
    """ From the list of the neighbors for a specific atom of reference, list_neighbors, return the distances from this 
    atom for each atom type in a dictionary."""
    list_neighbors = sorted(list_neighbors, key= itemgetter(1, 2))
    dic_distance_atom = {}
    for j in range(len(list_neighbors)):
        if list_neighbors[j][1] in dic_distance_atom : 
            dic_distance_atom[list_neighbors[j][1]].append(list_neighbors[j][2])
        else : 
            dic_distance_atom[list_neighbors[j][1]] = [list_neighbors[j][2]]
    return dic_distance_atom

print('List of the neighbors for a specific atom of reference:')
print(list_all_neighbors[1][41], '\n')
dic_atom_i = class_neighbors(list_all_neighbors[1][41])
print('Neighbors grouped by atom type and sorted in ascending order for the distance:')
print(dic_atom_i, '\n')

def get_list_distances(dic_atom_i,type_atom):
    """ From: - the dictionary of distances for each type of atom, from a atom of reference
              - the dictionary of the maximums of neighbors for each atom type, type_atom
    Return the list of the distances order by ascending. If there is no neighbor of a specific atom type, set 0."""
    distances = []
    for key, value in type_atom.items() :
        if key in dic_atom_i:
            for i in range(len(dic_atom_i[key])) : 
                distances.append(dic_atom_i[key][i])
            for i in range(len(dic_atom_i[key]), value) : 
                distances.append(0)
        else : 
            for i in range(value): 
                distances.append(0)
    return distances
print('List of the distance order by the previous dictionnary:')
print(get_list_distances(dic_atom_i,dic_all_types), '\n')


List of the neighbors for a specific atom of reference:
[[29, 'O', 1.5787762843840065], [30, 'O', 1.6792019993926566], [0, 'Al', 3.226658450990714], [21, 'O', 4.018323624679267], [27, 'O', 4.198413268295706], [25, 'O', 4.597726319507452], [19, 'O', 5.540916316997791], [14, 'O', 5.855860846368702], [38, 'Si', 6.077268148662403], [35, 'Si', 6.301345535078604], [24, 'O', 6.398725961359146], [22, 'O', 6.883358416437047], [7, 'O', 7.2637727153269545], [39, 'Si', 7.567778645771182], [12, 'O', 7.7819650009910974], [37, 'Si', 8.165082114215778], [18, 'O', 8.240781936512354], [26, 'O', 8.275467725041082], [23, 'O', 8.342630041336772], [17, 'O', 9.558257708994331], [31, 'Si', 10.370024419115662], [9, 'O', 10.615814078724782]] 

Neighbors grouped by atom type and sorted in ascending order for the distance:
{'Al': [3.226658450990714], 'O': [1.5787762843840065, 1.6792019993926566, 4.018323624679267, 4.198413268295706, 4.597726319507452, 5.540916316997791, 5.855860846368702, 6.398725961359146, 6.883

In [8]:
def create_row(list_all_neighbors,dic_all_types) : 
    """ From: - the list of all the neighbors of a configuration, list_all_neighbors
              - the dictionary of the maximums of neighbors for each atom type, type_atom
    Return a row vector with all the distances for all the atoms of references. """   
    distance_data = np.zeros((len(list_all_neighbors),sum(dic_all_types.values())))
    for i in range(len(list_all_neighbors)) : 
        dic_distance_atom_i = class_neighbors(list_all_neighbors[i])
        distance_data[i,:] = get_list_distances(dic_distance_atom_i,dic_all_types)
    #print(get_list_distances(dic_distance_atom_i,dic_all_types)) #Pour tester
    distance_data = np.ravel(distance_data)#, (1,len(list_all_neighbors[0])*sum(dic_all_types.values())))
    return distance_data


print('Creation of the row composed of all the distances of the neighbors for all the atom of reference (for one configuration):')
print(create_row(list_all_neighbors[1],dic_all_types)[-31:],'\n') #test for the following function

Creation of the row composed of all the distances of the neighbors for all the atom of reference (for one configuration):
[ 3.22665845  0.          0.          0.          0.          0.
  0.          1.57877628  1.679202    4.01832362  4.19841327  4.59772632
  5.54091632  5.85586085  6.39872596  6.88335842  7.26377272  7.781965
  8.24078194  8.27546773  8.34263004  9.55825771 10.61581408  6.07726815
  6.30134554  7.56777865  8.16508211 10.37002442  0.          0.
  0.        ] 



In [9]:
def data_array(all_atom, radius) : 
    """ From the atoms extraced from ASE in the feature all_atom and the radius, return an numpy array
    with all the distances for all the atoms of references. """ 
    array_neighbors, dic_all_types = all_config_neighbors(all_atom, radius)
    final_data = np.zeros((len(all_atom),42*sum(dic_all_types.values())))
    for i in range(len(array_neighbors)) : 
       final_data[i,:] = create_row(array_neighbors[i], dic_all_types)
    return final_data, dic_all_types

print('Final data array:')
print(data_array(atoms_2, 4),'\n')

print('Final data array of the last atom of reference (test for the previous function):')
print(data_array(atoms_2, 4)[0][1,31*41:])

Final data array:
(array([[0.        , 4.17265254, 2.38862119, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.17611891, 2.38794089, ..., 0.        , 0.        ,
        0.        ]]), {'Al': 1, 'C': 1, 'H': 5, 'O': 16, 'Si': 8}) 

Final data array of the last atom of reference (test for the previous function):
[ 3.22665845  0.          0.          0.          0.          0.
  0.          1.57877628  1.679202    4.01832362  4.19841327  4.59772632
  5.54091632  5.85586085  6.39872596  6.88335842  7.26377272  7.781965
  8.24078194  8.27546773  8.34263004  9.55825771 10.61581408  6.07726815
  6.30134554  7.56777865  8.16508211 10.37002442  0.          0.
  0.        ]


<a name="launch"></a>
## Dataset creation

First of all, we convert our data whose type is *atoms* into a *panda* data frame.
The 2nd file downloaded above is our target value. We will just make transformation of this value : for our future predictions, we will try to predict the *adsorption energy*, difference between this value and the potential energy of the molecule depending on his structure. We also subtract the mean of the adsorption energy in order to center the values.

In [10]:
def data_frame(all_atom, radius) : 
    """ From the atoms extraced from ASE in the feature all_atom and the radius, return the final data frame."""
    start = timeit.default_timer()
    
    # Features
    data, dic_all_types = data_array(all_atom, radius)
    name = []
    for key, val in dic_all_types.items() :
        for i in range(val) : 
            name.append(str(key)+' '+str(i+1)) 
    name = sorted(name, key=itemgetter(0))
    distance_table = pd.DataFrame(columns = name*42 )
    df2 = pd.DataFrame(data, columns =  name*42 )
    distance_table = distance_table.append(df2)
    
    # Target - adsorption energy
    adsorption_energy = []
    energy_data = pd.Series.tolist(data_energy.Energy)
    for i in range(len(atoms_200)): # Get energy of atoms
        adsorption_energy.append(atoms_200[i].get_potential_energy() - energy_data[i])
    mean_energy = np.mean(adsorption_energy)
    adsorption_energy = [adsorption_energy[i] - mean_energy for i in range(len(adsorption_energy))] # Subtract the mean of the adsorption energy   
    distance_table['Energy'] = pd.Series(adsorption_energy)
    
    stop = timeit.default_timer()
    print("Processing time: %0.2f s" % (stop - start))
    return distance_table

In [11]:
data_frame(atoms_2, 4)

Processing time: 6.87 s


Al 1       C 1       H 1       H 2       H 3  H 4  H 5       O 1       O 2  \
0   0.0  4.172653  2.388621  3.504808  3.878122  0.0  0.0  1.687689  1.712646   
1   0.0  4.176119  2.387941  3.473500  3.831084  0.0  0.0  1.676656  1.688743   

        O 3  ...       O 16      Si 1      Si 2      Si 3      Si 4  \
0  1.741808  ...   0.000000  6.072488  6.290598  7.550399  8.146431   
1  1.815746  ...  10.615814  6.077268  6.301346  7.567779  8.165082   

        Si 5  Si 6  Si 7  Si 8    Energy  
0  10.333766   0.0   0.0   0.0 -0.006111  
1  10.370024   0.0   0.0   0.0 -0.046628  

[2 rows x 1303 columns]

<a name="launch"></a>
## Dataset copy

We will copy the final dataset. The goal is to store it and to save computation time: when we will use it, we shall not run the kernel.  
We save it in [pickle](https://docs.python.org/3/library/pickle.html#module-pickle) format.

In [12]:
# The below script lasts around 10 minutes
data_distance = data_frame(atoms_200, 4)
data_distance.head()
data_distance.to_pickle("./data_distance.pkl")

Processing time: 789.08 s


In [13]:
data_distance_new = pd.read_pickle("./data_distance.pkl")
data_distance_new

Al 1       C 1       H 1       H 2       H 3       H 4  H 5       O 1  \
0     0.0  4.172653  2.388621  3.504808  3.878122  0.000000  0.0  1.687689   
1     0.0  4.568290  2.468720  4.022415  4.214737  0.000000  0.0  1.703726   
2     0.0  4.513681  2.613852  4.020059  4.122451  6.014900  0.0  1.628690   
3     0.0  4.343103  2.359981  3.557888  4.507440  6.388042  0.0  1.690680   
4     0.0  4.525015  2.542304  3.917335  4.521628  5.731700  0.0  1.670785   
5     0.0  4.566327  2.397627  3.986776  4.109491  0.000000  0.0  1.656780   
6     0.0  0.000000  2.516616  4.348064  4.456895  0.000000  0.0  1.726760   
7     0.0  0.000000  2.634911  4.173831  0.000000  0.000000  0.0  1.732745   
8     0.0  0.000000  2.390620  4.512519  0.000000  0.000000  0.0  1.695430   
9     0.0  0.000000  2.392000  3.935473  4.555629  0.000000  0.0  1.672317   
10    0.0  0.000000  2.392135  4.482416  4.497646  4.538280  0.0  1.692620   
11    0.0  0.000000  2.274961  4.120068  5.902563  0.000000  0.0  1.641928   
12    0.0  4.248685  2.520832  3.524922  5.991036  0.000000  0.0  1.708671   
13    0.0  4.495209  2.280167  4.192447  4.258701  4.341142  0.0  1.616887   
14    0.0  4.286268  2.447460  3.334668  6.195444  0.000000  0.0  1.676063   
15    0.0  0.000000  2.568048  3.953728  0.000000  0.000000  0.0  1.716242   
16    0.0  0.000000  2.286736  4.302068  4.465549  0.000000  0.0  1.680763   
17    0.0  0.000000  2.399286  0.000000  0.000000  0.000000  0.0  1.727313   
18    0.0  0.000000  2.661015  4.469422  6.181097  0.000000  0.0  1.699364   
19    0.0  0.000000  2.613651  4.310518  4.505322  0.000000  0.0  1.658090   
20    0.0  0.000000  2.715709  4.367741  0.000000  0.000000  0.0  1.696553   
21    0.0  0.000000  2.346327  0.000000  0.000000  0.000000  0.0  1.712418   
22    0.0  0.000000  2.523204  0.000000  0.000000  0.000000  0.0  1.640201   
23    0.0  0.000000  2.504116  0.000000  0.000000  0.000000  0.0  1.666992   
24    0.0  0.000000  2.306380  4.575777  0.000000  0.000000  0.0  1.707326   
25    0.0  0.000000  2.490245  3.988117  0.000000  0.000000  0.0  1.657822   
26    0.0  0.000000  2.257088  3.911952  4.596783  0.000000  0.0  1.699746   
27    0.0  4.056907  2.441407  3.345969  4.030452  4.402601  0.0  1.703772   
28    0.0  4.516514  2.466821  4.091106  4.331673  0.000000  0.0  1.684298   
29    0.0  0.000000  2.413991  4.452697  0.000000  0.000000  0.0  1.697272   
..    ...       ...       ...       ...       ...       ...  ...       ...   
170   0.0  0.000000  2.465827  4.380223  4.460955  0.000000  0.0  1.671421   
171   0.0  4.430826  2.443250  3.545205  4.293018  0.000000  0.0  1.641474   
172   0.0  0.000000  2.301895  4.082831  4.456098  0.000000  0.0  1.704068   
173   0.0  0.000000  2.440013  0.000000  0.000000  0.000000  0.0  1.671574   
174   0.0  0.000000  2.478237  0.000000  0.000000  0.000000  0.0  1.707145   
175   0.0  4.372458  2.421463  3.256192  0.000000  0.000000  0.0  1.693055   
176   0.0  0.000000  2.493158  3.714034  0.000000  0.000000  0.0  1.627956   
177   0.0  0.000000  2.425912  3.922607  6.109846  0.000000  0.0  1.668692   
178   0.0  4.242130  2.461566  3.352126  4.263234  0.000000  0.0  1.726796   
179   0.0  0.000000  2.287806  4.520832  6.557314  0.000000  0.0  1.649804   
180   0.0  0.000000  2.470176  0.000000  0.000000  0.000000  0.0  1.698601   
181   0.0  0.000000  2.470263  6.170022  0.000000  0.000000  0.0  1.699661   
182   0.0  0.000000  2.303039  0.000000  0.000000  0.000000  0.0  1.696880   
183   0.0  0.000000  2.464847  0.000000  0.000000  0.000000  0.0  1.658060   
184   0.0  0.000000  2.539163  0.000000  0.000000  0.000000  0.0  1.721010   
185   0.0  0.000000  2.399812  0.000000  0.000000  0.000000  0.0  1.715426   
186   0.0  0.000000  2.358584  0.000000  0.000000  0.000000  0.0  1.708715   
187   0.0  0.000000  2.440384  4.042428  0.000000  0.000000  0.0  1.670912   
188   0.0  0.000000  2.583972  4.421829  0.000000  0.000000  0.0  1.697908   
189   0.0  0.000000  2.3169

In [15]:
inv_data_distance = 1/data_distance_new
inv_data_distance = inv_data_distance.replace([np.inf, -np.inf], 0)
inv_data_distance.Energy = data_distance.Energy
inv_data_distance.to_pickle("./inv_data_distance.pkl")
inv_data_distance

Al 1       C 1       H 1       H 2       H 3       H 4  H 5       O 1  \
0     0.0  0.239656  0.418652  0.285322  0.257857  0.000000  0.0  0.592526   
1     0.0  0.218900  0.405068  0.248607  0.237263  0.000000  0.0  0.586949   
2     0.0  0.221549  0.382577  0.248753  0.242574  0.166254  0.0  0.613991   
3     0.0  0.230250  0.423732  0.281066  0.221855  0.156542  0.0  0.591478   
4     0.0  0.220994  0.393344  0.255276  0.221159  0.174468  0.0  0.598521   
5     0.0  0.218994  0.417079  0.250829  0.243339  0.000000  0.0  0.603580   
6     0.0  0.000000  0.397359  0.229987  0.224371  0.000000  0.0  0.579119   
7     0.0  0.000000  0.379519  0.239588  0.000000  0.000000  0.0  0.577119   
8     0.0  0.000000  0.418302  0.221606  0.000000  0.000000  0.0  0.589821   
9     0.0  0.000000  0.418060  0.254099  0.219509  0.000000  0.0  0.597973   
10    0.0  0.000000  0.418037  0.223094  0.222339  0.220348  0.0  0.590800   
11    0.0  0.000000  0.439568  0.242714  0.169418  0.000000  0.0  0.609040   
12    0.0  0.235367  0.396694  0.283694  0.166916  0.000000  0.0  0.585250   
13    0.0  0.222459  0.438564  0.238524  0.234813  0.230354  0.0  0.618472   
14    0.0  0.233303  0.408587  0.299880  0.161409  0.000000  0.0  0.596636   
15    0.0  0.000000  0.389401  0.252926  0.000000  0.000000  0.0  0.582668   
16    0.0  0.000000  0.437304  0.232446  0.223937  0.000000  0.0  0.594968   
17    0.0  0.000000  0.416791  0.000000  0.000000  0.000000  0.0  0.578934   
18    0.0  0.000000  0.375797  0.223743  0.161784  0.000000  0.0  0.588456   
19    0.0  0.000000  0.382607  0.231991  0.221960  0.000000  0.0  0.603104   
20    0.0  0.000000  0.368228  0.228951  0.000000  0.000000  0.0  0.589431   
21    0.0  0.000000  0.426198  0.000000  0.000000  0.000000  0.0  0.583970   
22    0.0  0.000000  0.396321  0.000000  0.000000  0.000000  0.0  0.609681   
23    0.0  0.000000  0.399342  0.000000  0.000000  0.000000  0.0  0.599883   
24    0.0  0.000000  0.433580  0.218542  0.000000  0.000000  0.0  0.585711   
25    0.0  0.000000  0.401567  0.250745  0.000000  0.000000  0.0  0.603201   
26    0.0  0.000000  0.443049  0.255627  0.217543  0.000000  0.0  0.588323   
27    0.0  0.246493  0.409600  0.298867  0.248111  0.227138  0.0  0.586933   
28    0.0  0.221410  0.405380  0.244433  0.230858  0.000000  0.0  0.593719   
29    0.0  0.000000  0.414252  0.224583  0.000000  0.000000  0.0  0.589181   
..    ...       ...       ...       ...       ...       ...  ...       ...   
170   0.0  0.000000  0.405543  0.228299  0.224167  0.000000  0.0  0.598293   
171   0.0  0.225692  0.409291  0.282071  0.232936  0.000000  0.0  0.609209   
172   0.0  0.000000  0.434425  0.244928  0.224412  0.000000  0.0  0.586831   
173   0.0  0.000000  0.409834  0.000000  0.000000  0.000000  0.0  0.598239   
174   0.0  0.000000  0.403513  0.000000  0.000000  0.000000  0.0  0.585773   
175   0.0  0.228704  0.412973  0.307107  0.000000  0.000000  0.0  0.590648   
176   0.0  0.000000  0.401098  0.269249  0.000000  0.000000  0.0  0.614267   
177   0.0  0.000000  0.412216  0.254932  0.163670  0.000000  0.0  0.599272   
178   0.0  0.235731  0.406245  0.298318  0.234564  0.000000  0.0  0.579107   
179   0.0  0.000000  0.437100  0.221198  0.152501  0.000000  0.0  0.606133   
180   0.0  0.000000  0.404830  0.000000  0.000000  0.000000  0.0  0.588720   
181   0.0  0.000000  0.404815  0.162074  0.000000  0.000000  0.0  0.588353   
182   0.0  0.000000  0.434209  0.000000  0.000000  0.000000  0.0  0.589317   
183   0.0  0.000000  0.405705  0.000000  0.000000  0.000000  0.0  0.603114   
184   0.0  0.000000  0.393831  0.000000  0.000000  0.000000  0.0  0.581054   
185   0.0  0.000000  0.416699  0.000000  0.000000  0.000000  0.0  0.582946   
186   0.0  0.000000  0.423983  0.000000  0.000000  0.000000  0.0  0.585235   
187   0.0  0.000000  0.409772  0.247376  0.000000  0.000000  0.0  0.598476   
188   0.0  0.000000  0.387001  0.226151  0.000000  0.000000  0.0  0.588960   
189   0.0  0.000000  0.4316

---
Back to [top](#top).